version: "2"

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: true
    config:
      threshold: #language-specific defaults. overrides affect all languages.

plugins:
  eslint:
    enabled: true
    channel: "eslint-8"
  csslint:
    enabled: true
#   rubocop:
#     enabled: true
#     channel: "rubocop-0-79"

exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "samples/"
- "features/"
- "artifacts/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "**/vendor/"
- "**/dist/"
- "**/lib/"
- "**/*_test.go"
- "**/*.d.ts"
