services:
  yacaba.web:
    image: ${DOCKER_REGISTRY-}yacaba-web
    build:
      context: .
      dockerfile: Yacaba.Web/Dockerfile

  db:
    image: postgres
    environment:
      POSTGRES_DB: yacaba
      POSTGRES_USER: yacaba
      POSTGRES_PASSWORD: yacaba

  pgAdmin:
    image: dpage/pgadmin4
    environment:
        CHECK_EMAIL_DELIVERABILITY: false
        ALLOW_SPECIAL_EMAIL_DOMAINS: local.dev
        PGADMIN_DEFAULT_EMAIL: yacaba@local.dev
        PGADMIN_DEFAULT_PASSWORD: yacaba